### ISSUE TITLE
synchronisation of bonsai H1 and H2 events with photometery system

### ISSUE THREAD

**Issue by EleonoraAmbrad** [neurogears/vestibular-vr#56] opened 2024-05-15 12:41 UTC
we would like to implement synchronisation between the data acquired via H1 and H2 and a photometry setup when using the Main experiment workflow.

https://www.rwdstco.com/product-item/dual-color-fiber-photometry-system/?_gl=1*r9q6pp*_up*MQ..*_ga*MTc5NzE1ODA1MS4xNzE1Nzc1MzE0*_ga_2P56W6VQP2*MTcxNTc3NTMxMy4xLjEuMTcxNTc3NTMzMi4wLjAuMA..&gclid=CjwKCAjwupGyBhBBEiwA0UcqaBYzOFXJ-Fceqbl8VPrT6yq4bXvHe9BTilrouICISsTUCkpdJtkFxxoCX_MQAvD_BwE (link to setup)

at the moment, a digital output of the ONIX is used to send a continuous 5V pulse to the RWD input to signal visual stimulus onset in a different workflow, but this approach is not optimal.

additionally, synchronisation with Harp devices would be required to align calcium imaging data to pupil tracking cameras and flow sensor data. Help with this would be greatly appreciated once we set up clock sync on H1 and H2!

**Comment by ederancz** [comment] 2024-07-01 13:47
Requirements: 

1. Bonsai to generate pseudorandom TTL pulse and send it out of ONIX digital out. These need to be logged with HARP timestamps. 
2. This has to be implemented in a duplicate insertion.workflow to contain an ONI node.

**Comment by RoboDoig** [comment] 2024-07-08 14:49
This all makes sense, just wondering about point 2. though - is there an advantage to using a premade csv file for the ON/OFF states vs. generating them online and logging the order for each experiment?

**Comment by EleonoraAmbrad** [comment] 2024-07-08 15:44
we were maybe thinking it's easier, but if not then generating online is also an option of course

**Comment by RoboDoig** [comment] 2024-07-08 16:00
My thinking is along these lines:

If you have a predetermined ON/OFF timing sequence loaded from .csv you have to load it into the workflow at runtime, which is fine. There may be a situation where you generate a few different .csv files for this, and you need to log somewhere which one you have used in Bonsai. This can be as simple as logging the name of the .csv file used, or you could 'relog' the entire file along with everything else to be 100% sure which sequence you used for synchronisation.

I can imagine a tricky situation happening somewhere down the line where you have been using a sequence file ('sequence.csv') and then at some point it's decided to change the sequence for some reason. The name of the logged file is the same but the sequence is different leading to potential confusion in later analysis.

This needs to be avoided, so to be safe we need to log the entire sequence anyway along with the corresponding HARP timestamps. Since this all needs to be logged anyway, to me it makes sense to just generate the sequence online in Bonsai. Unless there is some advantage of a predetermined sequence that I'm missing. Additionally, you can effectively have a predetermined sequence while generating it online by setting a seed for your random generator in the workflow.

**Comment by RoboDoig** [comment] 2024-07-11 16:47
I've implemented a photometry sync signal in the photometry-sync branch. The signal is set on digital output 0 of the ONIX. To fully test we need to route that signal to the photometry setup and also reroute it to a digital input on the ONIX so we can ensure that it's being logged correctly with HARP timestamps.

**Comment by EleonoraAmbrad** [comment] 2024-07-16 05:20
the photometry sync signal works well! as discussed, we would need the signal to stop right after the trial logic is over, to signal that the experiment is also finished (at the moment the TTL is still ON after the trial logic ends).

**Comment by RoboDoig** [comment] 2024-07-16 12:41
I branched the digitalOUT from pin 0 to the A1 pin on ONIX

**Comment by EleonoraAmbrad** [comment] 2024-07-16 12:42
i branched out the digitalO0 to A1 on onix

**Comment by RoboDoig** [comment] 2024-07-17 10:12
I would suggest branching instead to a digital input line, the reason being that each digital input event is HARP timestamped, whereas the analog data is acquired and timestamped in chunks. Practically this might not make that much difference to your synchronisation precision, but if you ever e.g. change the chunk size of the analog inputs it might have an effect.

**Comment by RoboDoig** [comment] 2024-07-17 10:25
Depending on the ONIX board you have, there is an issue with the HARP clock physical input. For certain versions of the ONIX board (I think this is an issue with 1.5B) the HARP clock jack actually sends a HARP clock signal OUT rather than receives the clock from an external device. Our design for the system relies on the ONIX board receiving the HARP clock from an external device.

My understanding is that they originally intended the ONIX boards to act as master HARP clocks sending clock signals out to other devices and then changed the direction in later versions.

To fix this at a hardware level, there is an adapter developed at OEPS that allows the ONIX board to receive HARP clock signals as input. I am asking Filipe how to obtain this. For now since the digital inputs of the ONIX are paired with HARP timestamps in the Bonsai workflow I suggest that we add another digital output --> digital input loopback in ONIX that can be used to synchronise HARP with the ONIX.

Potential solutions summarised:

1. Get a HARP clock adapter for ONIX from Filipe
2. Create another DO --> DI loopback in ONIX so that we can use DI events to synchronise with HARP
3. Depending on whether the photometry system is capable of recording at a high enough sampling rate, just speed up the photometry sync signal (rather than going for option 2)
4. Investigate whether the clock synchroniser device can be used as a repeater for the ONIX clock output.

Also please double check what version of the ONIX breakout board you have so we can confirm this is an issue that needs to be addressed.

**Comment by EleonoraAmbrad** [comment] 2024-07-17 14:13
can confirm hat the board is the 1.5 B (beta). 

I am currently setting up the DO1->DI1 connection for the synchronistation and the DO0->DI0 for the photometry sync signal.
We cannot use the photometry sync signal for both purposes (option 3) because the analog IN is going to be sampled at rates between 10 and 30 Hz., so we should either revert the direction of the clock synchroniser device or use the digital loop while we wait for the adaptor.

**Comment by EleonoraAmbrad** [comment] 2024-07-17 14:58
done

**Comment by RoboDoig** [comment] 2024-07-18 12:49
Re: the sync signal stopping after trial logic is done. I assume by this you mean you want the sync signal to stop only after all blocks are done?

I'm not sure I understand why this is desirable as it creates some ambiguity when used as a trial logic signal as well as a photometry sync signal.

Consider the last block of the sequence, as the sync signal is switching high to low with a random time interval, if the last sync signal is a switch to low, followed by setting again at low for the end of the block sequence you would not know when the block had actually ended.

**Comment by RoboDoig** [comment] 2024-07-18 14:04
Should be fixed by #64, pending testing.

**Comment by RoboDoig** [comment] 2024-07-19 12:00
Confirmed working after testing.

**Closed by RoboDoig** 2024-07-19 12:00 UTC
Labels: critical, Phase3
